services:
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    volumes:
      - grafana-data:/var/lib/grafana
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin123"
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    ports: ["9100:9100"]
    volumes:
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /run
        target: /host/run
        read_only: true
    command:
      - "--path.rootfs=/host"
      - "--collector.wifi"
      - "--no-collector.hwmon"
    privileged: true
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    volumes:
      - type: volume
        source: alertmanager-config
        target: /etc/alertmanager
    ports:
      - "9093:9093"

volumes:
  grafana-data:
  alertmanager-config: